[package]
name = "array_sorting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
criterion = "0.3"

[[bench]]
name = "bench_sorts"
harness = false
html_reports = true